# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: /:permalink

gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown


t:
  en:
    home:
      name: "Home"
      url: "/en/"
    about:
      name: "About"
      url: "/en/about/"
  de:
    home:
      name: "Homepage"
      url: "/de/"
    about:
      name: "Über uns"
      url: "/de/about/"
